### ISSUE TITLE
Graphing Data

### ISSUE THREAD

**Issue by Wat-Poods** [Lever-age/leverage#10]
We switched form trying to figure out a way to dynamically display data to instead using static images on Sunday. I think we need to return to this concept. I can take charge to research options.

**Comment by BayoAdejare** [comment]
I second this and would like to help in the research.

**Comment by Wat-Poods** [comment]
List of possible charting software that we can use to start:

http://www.flotcharts.org/flot/examples/
https://plot.ly/
https://www.amcharts.com/javascript-charts/
https://d3js.org/
https://www.udacity.com/course/data-visualization-and-d3js--ud507
https://elegantt.com/
http://nvd3.org/
https://davidwalsh.name/angular-charts

**Comment by lottspot** [comment]
nvd3 wins! For now. In any case, it's what we've launched the MVP with, and I think we can consider this issue resolved
