### ISSUE TITLE
Organize the set of issue labels

### ISSUE THREAD

**Issue by sergeantbacon** [Lever-age/leverage#12]
I created new labels piecemeal as issues came in that needed labels. Probably better to think a bit more holistically and define a set of tags that will work for us long term.

The folks at Robin did [a really nice job](https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/). May just copy them.

**Comment by sergeantbacon** [comment]
Set these up in Lever-age/Leverage

**Comment by sergeantbacon** [comment]
Looks like new label structure might have been lost during the transfer of the repo. I'll re-do the updates.

**Comment by lottspot** [comment]
The multi-repo workflow lends itself to letting us define this on a per-repo basis
