### ISSUE TITLE
Set up organization

### ISSUE THREAD

**Issue by eamoncaddigan** [Lever-age/Leverage#13]
On Wednesday we discussed setting up a GitHub organization and having the repo live there (instead of keeping it under @BayoAdejare's name).

**Comment by eamoncaddigan** [comment]
(I recall @caseyvaughan volunteering to take the lead, but if I got that wrong this should totally be reassigned.)

**Comment by caseyvaughan** [comment]
I will give it a shot.

**Comment by caseyvaughan** [comment]
I invited everyone to the new org page Lever-age  as admins but am still working on how to get the waffle page to link to the new org page. Any body have any suggestions?

**Comment by caseyvaughan** [comment]
Ok. I believe they are both linked to the same waffle page.

**Comment by daksb** [comment]
it works for me. thanks @caseyvaughan

**Comment by sergeantbacon** [comment]
The only thing left to do here is to migrate the issues. Have tried https://github-issue-mover.appspot.com/ but it's not working.

https://github.com/IQAndreas/github-issues-import is another option.

**Comment by caseyvaughan** [comment]
I reached out to a Waffle assistant and was told to review the following page.  (https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts)
 
Here is her mesage in it's entirety
"Hi Casey,

When you fork a repo in GitHub, the issues won't be transferred to the organization, so they wouldn't be visible on the Waffle board either.

You could however, transfer the repo to the organization in GitHub, then the issues would come over and also appear on the new Waffle board. More info on transferring a repo here: https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts

Thanks!
Kelli"

**Comment by caseyvaughan** [comment]
Ill try and get to this ASAP but if anyone else has time feel free.

**Comment by jaccat** [comment]
@caseyvaughan I took a look but I think that maybe only @BayoAdejare can do this (although I might be wrong!). When I view the repository main page (the old one) I don't see a "settings" option, which should be next to "graphs".

The page you linked on transferring a repo was great though! One other thing, the instructions mention that "the target account must not have a repository with the same name, or a fork in the same network." Will this be an issue? Do we need to delete the fork on the new org page?

**Comment by BayoAdejare** [comment]
@caseyvaughan just reading this, and you are right about all the above. Only I can transfer the repo (done) and the names was a conflict. All those task is complete now so this issue should be done.

**Comment by caseyvaughan** [comment]
That is awesome! Thanks for your help:-)
