### ISSUE TITLE
Create additional columns to cater testing phase and etc

### ISSUE THREAD

**Issue by daksb** [Lever-age/Leverage#14]
Create additional columns to cater testing and etc

**Comment by daksb** [comment]
added testing column to our dashboard

**Comment by daksb** [comment]
thinking of adding one more column. any thoughts?

**Comment by caseyvaughan** [comment]
Any way to do a variance?

**Comment by daksb** [comment]
not yet in waffle. I see a feature request with open status. we could do it manually for now. https://github.com/waffleio/waffle.io/issues/1709

**Comment by sergeantbacon** [comment]
"Testing" should be changed to "Review". Not all of the work items will be related to code/applications, though all items should be peer reviewed before they are marked as complete.

The review step needs two stages. The first stage is when the owner of the issue completes the work and deems it ready for review. The second stage is when a team member picks up the issue and agrees to review it.

With those revisions, here are the kanban board lanes:
* Backlog
* Ready for Work
* In Progress
* Ready for Review
* In Review
* Done

Does this work for y'all?

**Comment by caseyvaughan** [comment]
Sounds like a good bench mark. What if we miss a step?

**Comment by sergeantbacon** [comment]
Could you give a little more detail on what you mean by missing a step? Maybe an example?

When I've used kanban to manage teams, the place where the process deviated the most from what I mentioned above is when a reviewer found a bug or similar issue with the work. In that case, the item moves back to the In Progress step.

Especially when items are complex and prone to bugs, the process iterates through the following cycle until both item owner and reviewer think they've nailed it:
1. Item owner finishes up, moves to (4) Ready for Review
2. Reviewer picks up item, moves to (5) In Review
3. Reviewer finds issue, discusses with item owner, sends back to (3) In Progress
4. Item owner solves problem, moves to (4) Ready for Review
5. Reviewer picks up item...
...
N. Reviewer successfully completes review, move to (6) Done.

**Comment by caseyvaughan** [comment]
Thanks for answering my question. What is the minimum number of people needed to take an item from Backlog to Done? I am thinking the answer is three. 

1.) to put the item into the backlog. 
2.) the one who works on the item.
3.) the one who reviews the item.

Just trying to figure out how to get involved in a useful way.

**Comment by sergeantbacon** [comment]
You could actually get the item done with two folks. For example:
1. Team Lead A moves item from Backlog to Ready for Work
2. Team Lead A does the work
3. Team Member B reviews and approves.

Could also be...
1. Team Lead A moves item from Backlog to Ready for Work
2. Team Member B does the work
3. Team Lead A reviews and approves.

**Comment by daksb** [comment]
@sergeantbacon  I like the swim lanes.

@caseyvaughan @sergeantbacon  Great Q&As 

Thanks everyone.

**Comment by eamoncaddigan** [comment]
I think Issue 17 should be addressed before we close this. Thoughts?

**Comment by eamoncaddigan** [comment]
#17 is closed. Somebody from the process/administration team should close this one too. :smiley:

**Comment by daksb** [comment]
done.
