### ISSUE TITLE
Most issues are showing up twice on the waffle.

### ISSUE THREAD

**Issue by eamoncaddigan** [Lever-age/Leverage#17]

**Comment by eamoncaddigan** [comment]
If you look at the sources on Waffle, our repo is now listed twice:
https://waffle.io/Lever-age/Leverage/settings/sources

If we can figure out how to remove one of those, that'll probably fix it. I have a hunch that we'll need to contact support.

**Comment by caseyvaughan** [comment]
I will contact help desk and see what they recommend.

**Comment by eamoncaddigan** [comment]
Thanks for taking care of this!
