### ISSUE TITLE
Conduct a principal component analysis of the data

### ISSUE THREAD

**Issue by sergeantbacon** [Lever-age/leverage#19]
Conduct a principal component analysis (PCA) of our data to see if we can reduce dimensionality. Fewer dimensions usually leads to reduced computational time and a set of features that a bit easier to explore and visualize.

**Comment by lottspot** [comment]
This should probably be broken out as an issue under the data-analysis repo (if it still needs to be addressed). In the interest of cleaning things up here, I'm going to close this one down.
