### ISSUE TITLE
Create user story

### ISSUE THREAD

**Issue by BayoAdejare** [Lever-age/leverage#24]

**Comment by crsmyz** [comment]
# User Story: Sprint 1

First Leverage user story breaking down the features into 6 tasks which can be divided among teams and a backlog which presents future tasks after sprint 1 has been completed to satisfaction.

### Task 1

- As a user I should have the ability to log in and out of the app using a username and password. Signing up for the app should prompt me for a user name and password, authenticate through email and have a system for reseting my password in place.

### Task 2

- As a user I should have the ability to save candidates under my account and have the my account remember saved candidates. Candidates can be either in office or running, and they should appear under a favorites/saved list where I can have quick access. (Maybe have a quick summary view for each candidate?)

### Task 3

- As a user I should have the ability to select from a list of candidates in office or running a campaign. List will fluctuate depending on if in an election season but I should see two distinct categories one for candidates in elections and ones elected to office.

### Task 4
 
- As a user I should have the ability to sort candidates based on what position they are in/running for. Perhaps we can work this into a seasonal tab in which we divide elected officials from candidates running for office? This would make sorting positions easier from a user perspective. Same sort method could be used for both categories.

### Task 5

- As a user I want to see donation data summarized by amount, donee zip code, and date. Could be culminated into a summary page for each official in which I could view all three data points.

### Task 6

- As a user I want to view the total amount contributed during a campaign broken down by the two categories of campaign finance. This can be another subcategory presented on the officials summary page with a link to a detailed breakdown on another page.

# Backlog

1. Ability to set multiple qualifiers such as show donors from zip code (X), giving >200.00, from wk ending 12/1/16 - 12/15/16
2. Use of icons such as carton of milk to represent donations below $4.00, movie ticket for donations >$4.00 - 20.00, set of tires >$500.00 etc.(universal icons that remove language barrier).
3. Ability to use a ticker and hover over rolling total raised per candidate. Open source library of ticker module available @(https://github.com/robinhood/ticker).
4. Ability to see number of donations meeting qualifications set by user in the following areas (amount, donee zip code & date).

**Comment by lottspot** [comment]
As we've reached the MVP, I think we can consider this task completed
