### ISSUE TITLE
Design document for data analyses

### ISSUE THREAD

**Issue by eamoncaddigan** [Lever-age/leverage#25]
It'll be useful to have guiding principles for how we approach data, especially as we move forward with new team members.

**Comment by eamoncaddigan** [comment]
I wrote up a first version and posted it to the wiki: https://github.com/Lever-age/leverage/wiki/Data-Manifesto

However, this seems like a good place to discuss things, and I'd like for at least one other person to sign off on it.

**Comment by caseyvaughan** [comment]
I agree with the following qualification. The qualification is as long as we strike a balance between the granularity of our categorization and amount of useful information that can be generated. In other words, the level of granulation should be weighed in relationship to how useful the data is to the user.  You did articulate that balance well in the manifesto but I wanted to call attention to the need for us to strike a balance. I support not calling out individual donors as I think we gain more then we lose by doing so. If voters are inclined to know specifics they can access the data via the city web site.

**Comment by eamoncaddigan** [comment]
Thanks for the feedback @caseyvaughan! I'll iron that out. I also changed the name to something a little more tame: https://github.com/Lever-age/leverage/wiki/Data-Design-Guidelines

**Comment by lottspot** [comment]
Looks like this one is long done
