### ISSUE TITLE
Separate repos for data pipeline and analysis?

### ISSUE THREAD

**Issue by eamoncaddigan** [Lever-age/leverage#26]
The data pipeline will scrape donation records from the BoE, clean it, and load it into the database. The analysis subproject looks at new ways of classifying the donations in the DB. People who are working on the public-facing application probably don't need to clone all of this code.

**Comment by eamoncaddigan** [comment]
I created a [data pipeline](https://github.com/Lever-age/data-pipeline) and [data analysis](https://github.com/Lever-age/donation-analysis) repository under the Lever-age organization.

**Comment by lottspot** [comment]
This one is long done
