### ISSUE TITLE
Root API endpoint throws an error

### ISSUE THREAD

**Issue by modpluz** [Lever-age/leverage#35]
Root API endpoint throws a flask error.

**Comment by lottspot** [comment]
Can you document the steps to reproduce (I know which error you're talking about, but just so it's documented here).

**Comment by modpluz** [comment]
**Steps to Reproduce:**

- Spin up API docker container
- Run `npm test` in the frontend directory

**Expected:**
 Landing/Races page to load.

**Actual:**
 Api Error: `jinja2.exceptions.TemplateNotFound` which is as a result of an error.html template not existing.
 ~The root cause of the actual 500 error is yet to be determined.~
The root cause was a mysql connection - `Access denied for user 'leverage'....`

**Comment by lottspot** [comment]
Ah so this is caused by #37

**Comment by modpluz** [comment]
So it would seem. Closing this off.
