### ISSUE TITLE
Update the data analysis and pipeline wiki page

### ISSUE THREAD

**Issue by eamoncaddigan** [Lever-age/leverage#4]
It doesn't have anything useful yet.

**Comment by eamoncaddigan** [comment]
It's here, BTW: https://github.com/BayoAdejare/PhillyDemHack/wiki/Data-analysis-and-pipeline-ideas.

**Comment by eamoncaddigan** [comment]
Wrote up some stuff. I'd be grateful if folks can take a look and leave feedback:

* [Analysis](https://github.com/Lever-age/Leverage/wiki/Data-analysis)
* [Pipeline](https://github.com/Lever-age/Leverage/wiki/Data-pipeline)

**Comment by sergeantbacon** [comment]
I'll have a look and give feedback.
