### ISSUE TITLE
Put together the process that a feature follows from submission to resolution/incorporation into the project

### ISSUE THREAD

**Issue by sergeantbacon** [Lever-age/leverage#5]

**Comment by daksb** [comment]
Anyone could create a user story/use case such as new feature, bug, enhancement to existing feature, data issues, IT issues, documentation and put them in the backlog.  

I propose that we should have a shorter sprint/iteration. Each cycle would last about 2-3 weeks. Each sprint team should execute following steps:
  
1. Team grooms an iteration backlog - Decides on what goes into ready to be worked/to-do list based on priority etc.
2. A story can be split into multiple tasks if necessary, team member self-assigns task and starts to work on it if member encounter obstacle, she/he can reach out to the team via slack or other channel 
3. Team should meet each week to go over their progress and/or to discuss impediments 
4. At the end of each iteration, we demo our work, then we could have retrospective 

We can continue to go thru this cycle until our product is stable and production ready.

Please feel free to add if I missed anything.

**Comment by sergeantbacon** [comment]
@daksb: That's a solid start.

Our challenge now is to adapt this base framework to accomodate the characteristics of our project and team. Off the top of my head, two of those characteristics are
* Team members may not be able to meet at a regular cadence
* A reasonable cadence might be monthly meetings instead of weekly
* A member's capacity to contribute can vary significantly over time

In particular, let's consider how we can maintain a tidy process but minimize the amount that one person's absence can limit the flow of work. It's important that anyone looking to pick up a new item to work on can do so without waiting for interaction from someone in the team that's coordinating the work. I think this relates to your step 1: grooming the backlog.

**Comment by lottspot** [comment]
I think this issue actually touches on some ideas that are really relevant to where we are right now with the MVP launch. We should roll this discussion into #28 in order to consolidate the conversation
