### ISSUE TITLE
Create documentation that explains the feature process flow to a new joiner

### ISSUE THREAD

**Issue by sergeantbacon** [Lever-age/leverage#6]
Dependent on #5

**Comment by daksb** [comment]
here is a post about on-boarding, perhaps we could modify little bit and adapt  

https://github.com/blog/2128-creating-a-new-contributor-on-ramp

**Comment by sergeantbacon** [comment]
This is a great model to follow. We can build the onboarding guide up over time as we figure out what skills we're looking for and how folks can contribute.

I added CONTRIBUTING.md to root so we can start building that up.

**Comment by daksb** [comment]
added steps for new comers to contribute

**Comment by sergeantbacon** [comment]
Awesome. I'll give it a review.

**Comment by sergeantbacon** [comment]
I've updated the page. @daksb, would you mind reviewing, please?

**Comment by daksb** [comment]
Sure. Everything looks good.

wow! Lots of newcomers joined too.
