### ISSUE TITLE
Catch API error in frontend. 

### ISSUE THREAD

**Issue by modpluz** [Lever-age/leverage#63]
**Description:**
At the moment, on the candidate detail page at least, if the API returns an error, the loading message displays forever.

**Steps to Reproduce:**
Navigate to the candidate detail page using any candidate slug. e.g. jim-kenney, lawrence-krasner

**Expected:**
A user friendly message notifying the user that an error has occurred.

**Actual:**
Loading message that displays forever.

**Comment by modpluz** [comment]
PR: https://github.com/Lever-age/frontend/pull/95/

**Comment by lottspot** [comment]
Closed by https://github.com/Lever-age/frontend/pull/95
